version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgreSQLx
    ports:
      - '2345:5432'
    volumes:
      - progresDB:/data/postgres
    env_file:
      - ./.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: postgresAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
volumes:
  progresDB:
